---
version: '2'
services:
    app42:
        build:
              context: ./
              dockerfile: Dockerfile
        volumes:
              - home/project:/home/App42PaaS-Java-MySQL-Sample/target
    deploy:
        build:
              context: ./
              dockerfile: Dockerfile2
        ports:
              - '8080:8080'
        volumes:
              - home/project:/var/lib/tomcat9/

    mysql:
        image:  mysql/mysql-server
        ports:
              - '3306:3306'
        environment:
            MYSQL_DATABASE: appdb
            MYSQL_USER: app42
            MYSQL_PASSWORD: qwerty123

volumes:
  volume1: