---
version: "3"
services:
    app42:
          build:
              context: ./
              dockerfile: Dockerfile
          volumes:
              - './home/project:/home/project'
    deploy:
        image: dockertn3/tomcat-alpine-msfonts:latest
        ports:
              - '8080:8080'
        volumes:
              - './home/project:/usr/local/tomcat/webapps'
        depends_on:
              - app42
    mysql:
        image: mysql:latest
        ports:
              - '3306:3306'
        environment:
            MYSQL_DATABASE: appdb
            MYSQL_USER: app42
            MYSQL_PASSWORD: qwerty123
        depends_on:
              - deploy
              
...
